version: '3.8'

services:

  db:
    image: mysql/mysql-server:8.0.26
    environment:
      MYSQL_DATABASE: 'sql_hospital'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '3536'
      MYSQL_ROOT_PASSWORD: 'root_password'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: 
      context: ./cliniconnect
    image: ghcr.io/caridade1706/backend:${TAG:-latest}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend_staff_website:
    build: 
      context: ./frontend/staff_website
      dockerfile: Dockerfile.prod
    image: ghcr.io/caridade1706/frontend_staff_website:${TAG:-latest}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  frontend_user_website:
    build: 
      context: ./frontend/user_website
      dockerfile: Dockerfile.prod
    image: ghcr.io/caridade1706/frontend_user_website:${TAG:-latest}
    ports:
      - "3001:3001" 
    depends_on:
      - backend


networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: