spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sql_hospital?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: 3536
  sql:
    init:
      mode: always
  jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect