spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sql_hospital?useSSL=false
    username: root
    password: 3536
  sql:
    init:
      mode: always


  #JPA Settings
  jpa.hibernate.ddl_auto: update



