name: Build application

on:
  push:
    branches:
      - TP-21-Set-UP-CD-Pipeline

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    env:
      PRODUCTION: true
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Check GitHub Token Permissions
      run: |
        echo "Checking GitHub token permissions..."
        curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://ghcr.io/v2/token

    - name: Build and push
      uses: docker/bake-action@v3
      with:
        push: true
        files: docker-compose.prod.yml
        workdir: .
        set: |
          *.cache-to=type=gha,scope=cached-stage,mode=max
          *.cache-from=type=gha,scope=cached-stage