name: Build and Deploy Application

on:
  push:
    branches:
      - main
      - TP-21-Set-UP-CD-Pipeline
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PRODUCTION: true
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v3
        with:
          push: true
          files: docker-compose.prod.yml
          workdir: .
          set: |
            *.cache-to=type=gha,scope=cached-stage,mode=max
            *.cache-from=type=gha,scope=cached-stage

  deploy:
    name: Deploy to VM UA
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy with docker-compose
        working-directory: .
        run: |
          docker compose -f compose.prod.yml pull
          docker compose -f compose.prod.yml up -d --remove-orphans
          docker container prune -f
          docker image prune -af
          docker builder prune
          
    # Uncomment if you want to use the SSH steps instead
    # steps:
    # - name: Checkout code
    #   uses: actions/checkout@v3

    # - name: Set up SSH
    #   uses: webfactory/ssh-agent@v0.5.3
    #   with:
    #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # - name: Copy files via SCP
    #   run: |
    #     scp -o StrictHostKeyChecking=no -r ./* robertorcastro@deti-tqs-09.ua.pt:~/TQS_Project_Group9/

    # - name: Deploy with SSH
    #   run: |
    #     ssh -o StrictHostKeyChecking=no robertorcastro@deti-tqs-09.ua.pt << 'EOF'
    #     cd ~/TQS_Project_Group9
    #     docker-compose down
    #     docker-compose up -d --build
    #     EOF
