# name: Deploy to VM UA

# on:
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v3
  
#       - name: Login to Github Packages
#         uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
  
#       - name: Deploy with docker-compose
#         working-directory: .
#         run: |
#           docker compose -f compose.prod.yml pull
#           docker compose -f compose.prod.yml up -d --remove-orphans
#           docker container prune -f
#           docker image prune -af
#           docker builder prune
          
#     # runs-on: self-hosted

#     # steps:
#     # - name: Checkout code
#     #   uses: actions/checkout@v3

#     # - name: Set up SSH
#     #   uses: webfactory/ssh-agent@v0.5.3
#     #   with:
#     #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#     # - name: Copy files via SCP
#     #   run: |
#     #     scp -o StrictHostKeyChecking=no -r ./* robertorcastro@deti-tqs-09.ua.pt:~/TQS_Project_Group9/

#     # - name: Deploy with SSH
#     #   run: |
#     #     ssh -o StrictHostKeyChecking=no robertorcastro@deti-tqs-09.ua.pt << 'EOF'
#     #     cd ~/TQS_Project_Group9
#     #     docker-compose down
#     #     docker-compose up -d --build
#     #     EOF