name: Deploy to VM UA

on:
  push:
    branches:
      - TP-21-Set-UP-CD-Pipeline

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via SCP
      run: |
        scp -o StrictHostKeyChecking=no -r ./* robertorcastro@deti-tqs-09.ua.pt:~/TQS_Project_Group9/

    - name: Deploy with SSH
      run: |
        ssh -o StrictHostKeyChecking=no robertorcastro@deti-tqs-09.ua.pt << 'EOF'
        cd ~/TQS_Project_Group9
        docker-compose down
        docker-compose up -d --build
        EOF